name: Daily Build

on:
  schedule:
    - cron: '30 19 * * *'  # 1:00 AM IST (Kolkata timezone = UTC+5:30)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(TZ='Asia/Kolkata' date +'%F'))" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/erp-ui:${{ steps.date.outputs.date }}
          build-args: |
            VITE_APP_API=${{ secrets.VITE_APP_API }}
